{% set name = "kubernetes" %}
{% set version = "1.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: k8s.io/kubernetes  # [not win]
    url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: 9a7c074340cde46c9fd0fa9a500951fa5568081473ba3b0195952d3631fa32da  # [not win]

    url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
    sha256: 7434f2107987abbcbdc3a238e13c619c5cd95f3acc2fed7ddcb3bfdf0b7b8bd7  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.13.*  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - rsync  # [not win]

test:
  commands:
    - hyperkube help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kube-scheduler --help  # [linux]
    - kubectl --help
    - kubelet --help  # [not osx]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: k8s.io/kubernetes/LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
