{% set name = "kubernetes" %}
{% set version = "1.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 9b561d0dbb511b1eb8471b43e389527e151f3548e54111eee0c1d8b6fefabf88  # [not win]
  patches:   # [not win]
    - 0001-unset-conda-go-compiler.diff  # [not win]

  url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
  sha256: d804eb9d3cbe1aa5ab345e919841a452b29224c064f67c32f46124f2f2db5285  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cgo') }} 1.12.17  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - rsync  # [not win]

test:
  commands:
    - hyperkube help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kube-scheduler --help  # [linux]
    - kubectl --help
    - kubelet --help  # [not osx]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
