{% set name = "kubernetes" %}
{% set version = "1.32.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/kubernetes/kubernetes/archive/v{{ version }}.tar.gz  # [not win]
    sha256: e7c0249f28c69c686f586150126b1ae8b4ea7f6fb5ff28dd38f309bd1dc15d69  # [not win]
    patches:   # [not win]
      - 0001-unset-conda-go-compiler.diff  # [not win]

  - url: https://dl.k8s.io/v{{ version }}/kubernetes-node-windows-amd64.tar.gz  # [win]
    sha256: e634b059e52a4293fa0a9a3c9dadb93bc0a9b4a4be6ffc60182cbe3332829f10  # [win]

build:
  skip: true  # [(osx and not arm64) or ppc64le or aarch64]
  number: 0

requirements:
  run:
    - {{ pin_subpackage('kubernetes-client', exact=True) }}
    - {{ pin_subpackage('kubernetes-node', exact=True) }}
    - {{ pin_subpackage('kubernetes-server', exact=True) }}  # [unix]


test:
  commands:
    - kubectl

    - kubelet --help
    - kube-proxy --help
    - kubeadm --help

    - kube-apiserver --help  # [unix]
    - kube-controller-manager --help  # [unix]
    - kube-scheduler --help  # [unix]

outputs:
  - name: {{ name }}-client
    script: client/build.sh  # [unix]
    script: client/bld.bat  # [win]
    test:
      script: client/test.sh
    requirements:
      build:
        - {{ stdlib("c") }}  # [unix]
        - {{ compiler('cgo') }}  # [unix]
        - {{ compiler('c') }}  # [unix]
        - bash >=4.2  # [unix]
        - make  # [unix]
        - rsync  # [unix]
        - jq  # [unix]
    about:
      license: Apache-2.0
      license_file: LICENSE
      license_file: LICENSES/  # [win]
      summary: Kubernetes client binaries

  - name: {{ name }}-node
    script: node/build.sh  # [unix]
    script: node/bld.bat  # [win]
    build:
      binary_relocation: false
    test:
      script: node/test.sh
    requirements:
      build:
        - {{ stdlib("c") }}  # [unix]
        - {{ compiler('cgo') }}  # [unix]
        - {{ compiler('c') }}  # [unix]
        - bash >=4.2  # [unix]
        - make  # [unix]
        - rsync  # [unix]
        - jq  # [unix]
    about:
      license: Apache-2.0
      license_file: LICENSE
      license_file: LICENSES/  # [win]
      summary: Kubernetes node binaries

  - name: {{ name }}-server
    build:
      skip: true  # [not unix]
    script: server/build.sh
    test:
      script: server/test.sh
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler('cgo') }}
        - {{ compiler('c') }}
        - bash >=4.2
        - make
        - rsync
        - jq
      run:
        - {{ pin_subpackage('kubernetes-node', exact=True) }}
    about:
      license: Apache-2.0
      license_file: LICENSE
      summary: Kubernetes server binaries

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # [not win]
  license_file: LICENSES/  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - dhirschfeld
