{% set name = "kubernetes" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: k8s.io/kubernetes  # [not win]
    url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: a8b2ee84ce38fa14404d7e56daa87aa2f2fb13e0114fb1150f294c992ab3f36c  # [not win]

    url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
    sha256: 35403befd13f4c3f5a0ef34558c55c68c0b08f18dac901af4ce5ceff112c67f0  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.12  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
    - rsync  # [not win]

test:
  commands:
    - hyperkube help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kube-scheduler --help  # [linux]
    - kubectl --help
    - kubelet --help  # [not osx]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: k8s.io/kubernetes/LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://docs.kubernetes.io
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
