appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: heMZr808cD2K+5el5n7tOCGH+2v3kfAUhP/0PSilyDsqWNmhXs3WsVYlAG2/EnahxB1Hj9ij0Y0kkAPFU/F5xsEOuyLx8oo0O9FcQ3gPoQRC0b/1+a8V1TKNM3Aem2xpuSUL9B+8YKRlIGIMua9nTPKzwer8IvAT0jDD089nF9v2T0bNZcD9zLNACf0BiJvZ9eA3Hy19yfC9QHzcjENxsUpoPB45VuuG+yj0oNiZJoiyFVaVi2i1y7TiWuethAOI/4rQyeAddVTXW7iVo3IvE1GjA7ElkWJ006TqCls9HxUqSmsWyjEBJkza56JIEno32aVrbbRARw1dJyfjXXmaXIR3dhVLz+LOXDz35QnDfDrRWE0Cz9htufooFVB0nL1Khw6odvJlAPXBihul+NZMIUIRE1HQpuKaCIOMTw1cxVwoTmM732RTPUyFj8JYOz5u71cnESrd9PvT4W+9un2Jy2pSYVxa1A7TLSz6LEC2zYsLh9VwO8VIYHUQKwL2UHBon9pWx55bQ31sMRsuXIIUjVnO1fHZsmpncXNlVh3qmgr5FkFvlKqFWhKf2wos8EGWj1ZUe4EwXDjErpkbVD1S43xdvzxnEG5z8EvsEQJ8aNWqPTZRR5G5PuQS9njdyNS2BKPY76kSJIZlZXA+7HgwKwcblUGCPifhD0idU0ZdMWU=}
provider:
  win: azure
bot:
   automerge: true
